### ISSUE TITLE
unable to run on 64 bit mac osx 10.11.6

### ISSUE THREAD

**Issue by popdynamite5511** [CrossCraft/CrossCraft-Classic-Server#4]
Here is the error 
dyld: Library not loaded: @rpath/libopenal.1.dylib
  Referenced from: /Users/user/Downloads/CC-Server-Mac/Classic-Server
  Reason: image not found
Trace/BPT trap: 5

seems to be a similar error as the one on the other crosscraft things

**Comment by IridescentRose** [comment]
Yeah, we will scrap that dependency

**Comment by IridescentRose** [comment]
Will be fixed in the new backend
